### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Lacyway** [project-fika/Fika-Dedicated#5]
- [x] Filter item sending dedi profiles
- [x] Sounds are being played on dedi, disable by default
- [x] Set to absolute lowest graphics by default
- [x] More elegant way to determine if a player is a dedicated host when loading in a remote profile
- [x] Handle different unnatural disconnect types
- [x] Add timeout to "Wait for other players to finish loading" for the dedicated host
- [x] Only show 'Use Dedicated' if one is available
- [x] Implement partial or no rendering
- [x] Add a Terragroup Labs access card to the dedicated clients inventory when needed
- [x] Send CustomWeather with request
- [x] Make .bat file ensure `Fika.Dedicated.dll` exists

**Comment by Lacyway** [comment]
For the last bulletin:
```batch
@echo off
if NOT EXIST ".\BepInEx\plugins\Fika.Dedicated.dll" (
    echo Could not find 'Fika.dedicated.dll', please install the dedicated plugin before starting the client.
    pause
) else (
    start "" EscapeFromTarkov.exe -token=$Profile$ -config={"BackendUrl":"http://127.0.0.1:6969","Version":"live"} & exit
)
```
